PRIMARY_BLM_7 = {
    1: [
        "BLMTI.06L3.B1I10_TCP.6L3.B1",
        "BLMTI.06L7.B1E10_TCP.D6L7.B1",
        "BLMTI.06L7.B1E10_TCP.C6L7.B1",
        "BLMTI.06L7.B1E10_TCP.B6L7.B1",
    ],
    2: [
        "BLMTI.06R3.B2E10_TCP.6R3.B2",
        "BLMTI.06R7.B2I10_TCP.B6R7.B2",
        "BLMTI.06R7.B2I10_TCP.C6R7.B2",
        "BLMTI.06R7.B2I10_TCP.D6R7.B2",
    ],
}

ADT_TRIGGER = "ADT{plane}.SR4.B{beam}:BLOWUP_RUNNING"
ADT_AMP = "ADT{plane}.SR4.B{beam}:BLOWUP_EXC_AMPLITUDE"
ADT_LENGTH = "ADT{plane}.SR4.B{beam}:BLOWUP_EXC_LENGTH"
ADT_GATE = "ADT{plane}.SR4.B{beam}:BLOWUP_GATING_DELAY"
ADT_MODE = "ADT{plane}.SR4.B{beam}:BLOWUP_EXC_MODE"
ADT_SIGNAL = "ADT{plane}.SR4.B{beam}:BLOWUP_EXC_SIGNAL"
# ADT_LENGTH = 'ADT{plane}.SR4.B{beam}:BLOWUP_EXC_LENGTH'

INTENSITY = "LHC.BCTFR.A6R4.B{beam}:BEAM_INTENSITY"
FILL_SCHEME = "LHC.STATS:LHC:INJECTION_SCHEME"
BUNCH_NUM = "LHC.STATS:B{beam}_NUMBER_BUNCHES"
ACCEL_MODE = "HX:AMODE"
BEAM_MODE = "HX:BMODE"
OPTICS_ID = "HX:OPTID"
# beta* same problem
ENERGY = "LHC.STATS:ENERGY"
# ENERGY = 'HX:ENG'

# 6h +-q
